<%@ Page Title="Terms of Service" Language="vb" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Terms.aspx.vb" Inherits="AspNetPortal._Terms" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
	<hr />

	<p>By using this web site, ("SERVICE"), you agree to be bound by the following terms and conditions ("Terms of Service").</p><p>AspNetPortal.XYZ, ("WE"), reserve the right to update and change these Terms of Service from time to time, without your approval or notice. Any new features that augment, remove or enhance the current SERVICE including the release of new tools and resources shall be subject to these Terms of Service. The use of the SERVICE after any such changes shall constitute your consent to such changes. If you do not agree nor accept these Terms of Service then stop using this SERVICE and abandon our servers immediately. You can review the most current version of the Terms of Service of this SERVICE at any time by visiting this web page.</p><h3>General Conditions</h3><ol><li>You must be over the age of 13 to use this SERVICE; otherwise, please abandon our SERVICE immediately.</li>
	<li>If you are UNDER the age of 18, please have your parent or guardian to approve your participation "in writing", before using this SERVICE.</li>
	<li>Your use of the SERVICE is at your sole risk. The SERVICE is provided to you and your customers on an "as is" and "as available" basis.</li>
	<li>You acknowledge that we do not guarantee that the SERVICE is free of from any defects or malfunctions. You will hold us harmless of any such defects even in the situations that we are aware of any problems or defects.</li>
	<li>You agree not to resell, duplicate, reproduce or exploit any part of the SERVICE without our express written permission.</li>
	<li>You can not use the SERVICE to store, host, or send unsolicited email (spam) or SMS messages.</li>
	<li>We may, but have no obligation to, remove content and Accounts containing content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service.</li>
	<li>You understand that the SERVICE can be used for transmission of your content, and that during processing your content, including invoices, payment reminders, and personal messages, may be transferred in an unencrypted form over the internet.</li>
	<li>You may not use the SERVICE to transmit any viruses, worms, or malicious content.</li>
	<li>We do not warrant that (i) the SERVICE will meet your specific requirements, (ii) the SERVICE will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the SERVICE will be accurate or reliable, (iv) the quality of any products, SERVICEs, information, or other material purchased or obtained by you through the SERVICE will meet your expectations, and (v) any errors in the SERVICE will be corrected.</li>
	<li>AspNetPortal.XYZ, its affiliates and its sponsors are neither responsible nor liable for any direct, indirect, incidental, consequential, special, exemplary, punitive or other damages arising out of or relating in any way to your use of the SERVICE. Your sole remedy for dissatisfaction with the SERVICE or any type of harm produced by the SERVICE, is to stop using the SERVICE.</li>
	<li>If any provision of the Terms of Service is held invalid or otherwise unenforceable, the enforceability of the remaining provisions shall not be impaired thereby.</li>
	<li>The failure of AspNetPortal.XYZ to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. This "Terms of Service" constitutes the entire agreement between you and AspNetPortal.XYZ, and govern your use of the SERVICE superseding any prior agreements between you and AspNetPortal.XYZ, (including, but not limited to, any prior versions of this Terms of Service).</li>
</ol><h3>Content Restrictions</h3><p>All services provided by us may be used for lawful purposes only. Transmission, storage, or presentation of any information, data or material in violation of any United States Federal, State or City law is prohibited. Some prohibited contents are (but not limited to) copyrighted material, material we judge to be unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable, or material protected by trade secret and other statute. The subscriber agrees to indemnify and hold harmless AspNetPortal.XYZ and its employees from any claims resulting from the use of the SERVICE which damages the subscriber or any other party.</p><h3>Copyright and Content Ownership</h3><ol><li>AspNetPortal.XYZ owns the intellectual property rights to any and all protectable components of the SERVICE, including but not limited to the name of the SERVICE, artwork and end-user interface elements contained within the SERVICE including many of the individual features and the related documentation. You may not copy, modify, adapt, reproduce, distribute, reverse engineer, decompile or dissemble any aspect of the SERVICE which we own.</li>
	<li>We claim no intellectual property rights over the Content you upload or provide to the SERVICE. However, by using the SERVICE, you agree that others, known or unknown to you may view, use and share your content.</li>
</ol><h3>Pornography is prohibited on our servers</h3><p>This includes accounts that promote, offer, display or sell sexually explicit or hardcore images and/or advertise sexually explicit products or SERVICEs. We allow some accounts of an adult nature, but we do not allow pornography nor sexually related products or SERVICEs. If you think your account may violate our Terms of Service, please ask us before signing up for an account so that we may determine if we can allow you to operate your business in our servers. AspNetPortal.XYZ reserves the right to determine what is and what isn't acceptable for our servers.</p><h3>MP3 and video files are prohibited on our servers</h3><p>Any MP3and/or video archives, downloads and streaming, is strictly prohibited in any shape or form. Use alternate SERVICEs like YouTUBE, VIMEO, etc. for that purpose. You are allowed to embed URLs in your posts, comments or issue details uploaded to our servers. AspNetPortal.XYZ will not allow users to store, offer downloads or streaming of copyrighted mp3's or video/audio files violating copyright laws. Any account found to be doing so will be removed immediately from our servers without notice and/or refund, even if it is within the initial period covered under our money back guarantee. We do allow audio or video files that are not copyrighted material to be stored, downloaded or streamed from our servers as long as they belong to the account holder.</p><h3>Promulgation of viruses is prohibited on our servers</h3><p>Using your account to store or distribute viruses is strictly prohibited. Any violation or activity, whether or not the intrusion results in the corruption or loss of data, will be investigated and proper action will be taken. The presence of any of these programs, whether or not run, will result in action against the user including suspension or termination without refund. Also prohibited are sites that promote any illegal activity or present content that may be damaging to AspNetPortal.XYZ's servers or any other server on the internet. Links to such materials are also prohibited. Examples of unacceptable content or links:</p><ul><li>Pirated software or serial numbers</li>
	<li>Hacker programs or archives</li>
	<li>Warez sites</li>
</ul><p>AspNetPortal.XYZ will be the sole arbiter as to what constitutes a violation of this provision. Accounts found to contain (or contain links to) pirated software, hacking or hacker programs will be shut down immediately and will not be allowed back on the server. Any information or files on these servers will be deleted shortly thereafter and you will never regain access to it.</p><h3>Transfer (Bandwidth)</h3><p>Each account is allowed a certain amount of bandwidth (please see our hosting plans page to see the amount allowed for your plan). Should a client exceed it's limit, there maybe an excess charge over the allocated amount. It should be noted that we seldom had an instance where a client has been billed for extra transfers. Most of our clients don't even come close to their limit per month. Please let us know if you have any questions about this and we would be glad to assist you.</p><h3>Commercial Advertising Email</h3><p>Since spamming is illegal in many states and countries we cannot afford to let spam mail pass through our servers under any circumstances. If you plan on using your account for unsolicited, bulk emailing please stop right here and do not sign up for an account with us. Should we discover that (1) you are sending spam through our servers -Or- (2) sending spam that links to pages on our servers, your account will be immediately deleted, terminated, blocked or deactivated without notice, and no refund of any kind will be made. AspNetPortal.XYZ will be the sole arbiter as to what constitutes a violation of this provision.</p><h3>Background Running Programs</h3><p>Clients are not allowed to operate any background processes without prior approval from AspNetPortal.XYZ. We may allow other non-abusive programs to run continually in the background but these are considered on a case-by-case basis and an extra charge will be incurred based on system resources used and operational maintenance needed. Note that any account found to be running background processes such as IRC bots, eggdrop, BitchX, port scanners will be suspended without prior notice.</p><h3>IRC</h3><p>IRC, IRC bots or IRC clients are strictly prohibited to be operated on our servers.</p>
	<h3>Account Terms</h3><ol><li>You acknowledge and certify that you are at least 18 year old and hold legal capacity to enter into any legal agreement.</li>
	<li>If you are UNDER the age of 18 you must have your parent or guardian approve your participation PRIOR your use of this SERVICE. Otherwise, please abandon this SERVICE immediately.</li>
	<li>You must provide your legal name, a valid email address, and any other information requested by this SERVICE in order to complete the signup process.</li>
	<li>Your login may only be used by one person - a single login shared by multiple users is not permitted.</li>
	<li>You are responsible for maintaining the security of your account and password.</li>
	<li>We cannot and will not be liable for any loss or damage from your failure to protect your login information, including your password.</li>
	<li>You are responsible for all content posted in the system, and for all the activity that occurs under your account (even when content is posted by others who have accounts under your account or had used you account with or without your consent).</li>
	<li>You may not use the SERVICE for any illegal or unauthorized purpose. You must not, in the use of the SERVICE, violate any laws in our or your jurisdiction (including but not limited to copyright laws).</li>
</ol><h3>Account Activation</h3><p>By signing up for any of the SERVICEs offered by AspNetPortal.XYZ, client agrees to hold AspNetPortal.XYZ and any and all of its officers, directors, stockholders and employees safe and harmless from any and all actions, policies, negligent and criminal acts that may be performed by client in connection with clients utilization of any and all SERVICEs provided by AspNetPortal.XYZ. The transfer of a domain owned by a client to a server utilized by AspNetPortal.XYZ or the use of our server so as to host a new domain shall constitute the beginning of the use of SERVICEs provided byAspNetPortal.XYZ by client regardless of whether or not client has paid for said SERVICEs at any given time.</p>
	<h3>Account Cancellation</h3>
	<p>In order to maintain our low fees, they are calculated on a 1 year term bases. We have a no-refund policy. In case a dispute arises regarding an early termination of SERVICE, we will have to charge you separately the prorated monthly charge fee you applied for, plus the initial setup fee ($155) for starting up your Call Center, and again a close down setup fee ($155) for closing down before the expiration or due date.</p>
	<p>When you need to cancel an account, please email us at: <a href="mailto:support@AspNetPortal.XYZ" rel="nofollow"><b>support@AspNetPortal.XYZ</b></a> and our billing representative will be in touch with you if it is applicable to your situation.</p>
	<p>If you would like to cancel your account before your Account is due for Renewal, please contact us at least 7 days prior to the date that you would like your account to be closed, or you may risk being automatically re-billed for the next billing term.</p>
	<p>AspNetPortal.XYZ will send you an email reminder one month prior to your renewal date. Should you decide to stay with AspNetPortal.XYZ or if you would like to cancel, please reply to our email and let us know at least 7 days prior to the renewal date.</p>
	<p>AspNetPortal.XYZ retains the right to change any or all of the above Policies, Guidelines, and Disclaimer from time to time as maybe required by law or as necessary in order to maintain the quality of SERVICE.</p>
	<ol>
		<li>You alone are responsible for the proper cancellation of your account.</li>
		<li>You may cancel your account from the "My Account" page after logging into your Account or by notifying us about your decision via email or by phone. If you are paying by PayPal, you are also responsible for canceling your PayPal subscription to prevent them from sending any further payments.</li>
		<li>All of your Content will be immediately deleted from the SERVICE upon cancellation.</li>
		<li>If you cancel the SERVICE before the end of your current paid up month or year, your cancellation will take effect immediately at the end of the current month or year, and you will not be charged again.</li>
		<li>AspNetPortal.XYZ, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the SERVICE for any reason at any time. Such termination of the SERVICE will result in the deactivation or deletion of your Account or your access to your Account, and the forfeiture and relinquishment of all Content in your Account. We reserves the right to cancel or refuse SERVICE to anyone for any reason at any time without refunds.</li>
</ol>
	<h3>Payment, Refunds, Upgrading and Downgrading Terms</h3>
<ol>
	<li>Free accounts are not required to provide any type of payment information.</li>
	<li>A valid credit card, electronic check or PayPal account is required to pay for the use of this SERVICE once the free trial period has ended.</li>
	<li>If you initially sign up for a FREE TRIAL and you do not cancel that account within 30 days, you will receive a notification e-mail after the TRIAL PERIOD allowing you to begin paying for your subscription. If you choose not to pay once your trial period has expired, your account will be suspended until payment is received. If you pay or enter your payment information before the 30-day, trial period should end, the trial ends on the same day and your billing period starts the same day as well. If payment is made after the 30 day period. Your SERVICE starts on the date you make the first payment. There are no additional charges for delayed payments.</li>
	<li>SERVICE is billed in advance on a monthly basis and is non-refundable. There will be no refunds or credits for partial months of SERVICE or early cancellations, upgrade/downgrade refunds, or refunds for months unused by an open account. In order to treat everyone equally, no exceptions will be made. If you insist on an early termination, we will have to charge you all SERVICEs itemized individually at the rate of $200 for setting up your account, and $200 for manually closing your account on the date you claim, additionally you will be charged an early termination fee of $150, plus your daily usage rate at the rate of 2 times the amount of each regular monthly rate divided by the days in the month you wish to cancel.&nbsp; For these reasons, we recommend everybody to just let the system handle all cancellations and expiration automatically.</li>
	<li>All fees are exclusive of taxes, levies, or duties imposed by taxing authorities, and you shall be responsible for paying such taxes, levies, or duties, excluding only United States (federal or state) taxes.</li>
</ol>
	<h3>Modifications to the Service and Fees</h3><ol><li>We reserve the right to modify, suspend, or discontinue this SERVICE at any time, for any reason, with or without notice.</li>
	<li>We reserve the right to change our fees at any time. Fee change notices may be posted to the SERVICE.</li>
	<li>If you wish to change your subscription or unsubscribe completely, please contact us at your earliest convenience.</li>
</ol>
	<h3>Server Abuse</h3>
	<p>Your account may not be used to interfere with or disrupt the SERVICE or servers or networks connected to AspNetPortal.XYZ, or disobey any requirements, procedures, policies or regulations of networks connected to AspNetPortal.XYZ . Any violation will result in immediate removal of your account and data from our servers, without notice and refund of any fees paid in advance.</p>
	<h3>Refusal of Service</h3>
	<p>Depending on the severity, we reserve the right to refuse, suspend, or cancel SERVICE, at our sole discretion if client violates any part of this Terms of Service. This is necessary in order to prevent further damage. We will take all reasonable efforts to rectify the violation with the customer before canceling a customer account.</p>
	<h3>Limitation of Liability</h3>
	<p>AspNetPortal.XYZ shall not be responsible for any claimed damages, including incidental and consequential damages, which may arise from AspNetPortal.XYZ servers going off-line or being unavailable for any reason whatsoever. Furthermore, AspNetPortal.XYZ shall not be responsible for any claimed damages, including incidental or consequential damages, resulting from the corruption or deletion of any web site, account, post, file or service from one of AspNetPortal.XYZ servers. All damages shall be limited to the immediate termination of SERVICE and the refund of the remaining unused amount paid in advance, if any.</p><h3>Reporting Abuse and Violations</h3><p>Violations of these Terms of Service should be reported to <a rel="nofollow" href="mailto:abuse@AspNetPortal.XYZ"><strong>abuse@AspNetPortal.XYZ</strong></a> All complaints will be investigated promptly.</p><h3>Questions and Suggestions</h3><p>If you have questions or suggestions, please write to <a rel="nofollow" href="mailto:support@AspNetPortal.XYZ"><strong>support@AspNetPortal.XYZ</strong></a></p>

</asp:Content>
